version: '3.4'

services:

  portal-ingress:
    image: nginx:1.23
    volumes:
    - ./ingress-nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
    - ./ingress-nginx.conf:/etc/nginx/nginx.conf:ro    
    ports:
    - ${ACROWEB3_NETWORK_EXPOSED_PORT}:80
    depends_on:
      - dds
